### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by johanboekhoven** [cb109/sublime3dsmax#15]
Hey,

I have a bunch of snippets to speed up my workflow, which probably makes not much sense for others, what would be the best way to add these to Sublime?

**Comment by cb109** [comment]
Hey, I just put my custom snippets into the User Package, e,g. `C:\Sublime Text 3 Portable\Data\Packages\User\snippets`. They must end in `.sublime-snippet`. Make sure they use the `<scope>source.maxscript</scope>` to work with .ms files only. I just copied them from example ones, e.g. those coming with this plugin.
