### ISSUE TITLE
Bidirectional communication ST-3dsMax?

### ISSUE THREAD

**Issue by brupelo** [cb109/sublime3dsmax#19]
Nice! today I've discovered the existence of this plugin and it's really promising, I'm gonna definitely give it a shot.

One question though, after seeing the demo video it seems you can easily send commands to interact with max... Now, I was wondering whether there is any chance to receive information from the max side (bidirectional communication).

Why am I asking this? I'd like to know how to make a plugin which is able to [export the max scene steps](https://gamedev.stackexchange.com/questions/150622/3ds-max-plugin-exporting-steps) and I was wondering whether this package could help me somehow with such a task.

Let's say, imagine you send your script to max and then you're able to read somehow some sort of max information like the scene data, that would open a lot of possibilities to render this information in the Sublime side (ie: python+pyopengl).

In any case, if you got any advice about this or my original question in that stackexchange site it'd be awesome ;)

**Comment by cb109** [comment]
To be honest I don't really understand what you are trying to do :) But I am pretty sure it's out of scope for a Sublime plugin.

In general, collecting output about 3ds Max actions will require you to run some MAXScript/Python inside it, which is usually synchronous and blocking and thus not a good idea to run all the time. Afaik there is no threading/async/background task support that works properly and all-purpose, neither with pymax nor any .NET hacks. Part from that 3ds Max is pretty secretive about its internals, I don't think you can get detailled access to the redo/undo stack contents and there is no usable logging output either. What the Macro recorder outputs is usually good enough to start a script based on it, but not more, many things are not output at all by it.

I'll gladly continue discussion here but it would help if you state again what you are actually trying to accomplish?

**Comment by brupelo** [comment]
@cb109 Hiya! Yeah, it totally makes sense what you're saying... Mmmm, alright, let's focus about the problem from a different perspective to check what can and what can't be done. Please take a look to [this](http://fernandojsg.com/project/3d-studio-max-tools/) plugin, now, tell me, how would you say that plugin is working behind the curtains?

PS: Today i've forked your project and tested it, it's great one, also i've felt the need to provide few [tweaks](https://github.com/cb109/sublime3dsmax/pull/20) ;)

**Comment by cb109** [comment]
With just looking at the article you linked, the plugin seems to aggregate scene information and export it to a custom file format. The author is most likely looping over scene geometry, animation controllers, materials and so on to collect data and arrange that as he sees fit. You can write both ASCII and binary files from maxscript, so you can output pretty much anything you want. 

Do you want to create something similar?

**Comment by brupelo** [comment]
Mmm, yeah, yesterday reading the page of that plugin I thought maybe was the case and he's just not querying the undo/redo max stack after all, dunno... Although still it'd be cool to know whether this is possible to do or not, added some [bounties](https://gamedev.stackexchange.com/questions/150622/3ds-max-plugin-exporting-steps) here so maybe others know more about it.

Well, kind of... that Kile's plugin is recreating the max scene with c++ code (i guess), the idea i got here in mind is creating a python max plugin (thanks autodesk to include python support in your products) to create procedural SDF scenes (shader code) out of max scenes in certain cases, for instance, using booleans in SDF maths is trivial... but applying modifiers like catmull-clark is just not possible (as these ones affect the mesh topology and SDF are just implicit equations at the end of the day).

Btw, talking about bidirectional communication, I think using the clipboard as an intermediate storage could work, ie: push state of the clipboard, run your max code, store the output on the clipboard, dump it in Sublime, pop clipboard. As far as I know the winapi send methods are synchronous, right?

**Comment by cb109** [comment]
Hm, I have no idea what SDFs are, but how does shader code have anything to do with booleans or subdivision modifiers? I am confused.

Using the clipboard would work yes, I've used [pyperclip](https://github.com/asweigart/pyperclip) in the past to handle this, it boils this down to simple copy/paste commands, nice library. You could also copy the Windows-relevant parts from it to avoid the dependency, it just needs the builtin `ctypes`. A simple file may also work, I am actually using that as the transport medium when submitting multiline scripts to 3ds Max (`SendSelectionToMaxCommand`).

**Comment by brupelo** [comment]
Hiya, sorry, I thought SDF would be a pretty familiar term, it's the acronymo of "Signed Distance Field". If you're interested, you can read some introductory material [here](https://www.scratchapixel.com/lessons/advanced-rendering/rendering-distance-fields) . Also, there is this website called [shadertoy](https://www.shadertoy.com/) where you'll find thousands of examples where people uses SDFs to model cool stuff. You can see they model 3d stuff by using SDFs, although  the "problem" is they create these SDFs manually with mathy formulas and that's quite slow and not artists friendly... that's what my idea is all about, generating SDFs with max's help.

In any case, about the clipboard thingy, finally I've decided to use QClipboard, which is a pyside2 cool class. The only thing, as you're already aware being that won't be available on old max versions, although for me that's not a problem as i'm using max2018, but... ;) .

Anyway, today I'll try to figure out whether the winapi send methods are synchronous or not, for instance, let's say i send a heavy computation to do in max-side and then i copy the results to the clipboard, can i be sure these results will be ready to go on Sublime side when max has finished? Well, let's see.

**Comment by cb109** [comment]
Thanks for the link. I am pretty confident those functions are synchronous, otherwise I'd have run into problems countless times already :D Good luck with your tool!
