### ISSUE TITLE
Possible Solution for #2

### ISSUE THREAD

**Issue by faggionluca** [cb109/sublime3dsmax#5]
hey,
before submitting a new pull request (sometimes sublime mocks me ), i have elaborated a new solution for #2 this involve the injection of the completions thought the sublime api instead of the .sublime-completions file
check it out 066a1865378c4277779eade637cad984dd9bd1cc

tested in both ST2 and ST2
![#2 fix](http://www.mediafire.com/convkey/47f8/nyk8n16ksvn0tuszg.jpg)

**Comment by cb109** [comment]
Just gave it a try and it works like a charm, great work :bow:! The code is much clearer now as well. Please submit a pull request to the `develop` branch, as I restrict the `master` to releases only. Thank you!

**Comment by cb109** [comment]
Closed due to #7
